package com.micheledaros.messaging.infrastructure

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class IDGeneratorTest {

    @Test
    fun `generateId generates and id with length 32`() {
        val id = generateId()
        assertThat(id.length).isEqualTo(32)
    }

    @Test
    fun `the ids generated by generateId() are unique`() {
        val idCount = 10
        val generatedIds = (1..idCount)
                .map { generateId() }
                .toSet()
        assertThat(generatedIds).hasSize(idCount)

    }


}