version: '3.1'
services:
  app:
    container_name: micheledaros-messaging
    image: micheledaros-messaging
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
      - rabbitmq
    environment:
      - spring_datasource_url=${DATASOURCE_URL}
      - spring_datasource_username=${DATASOURCE_USERNAME}
      - spring_datasource_password=${DATASOURCE_PASSWORD}
      - spring_datasource_jpa+hibernate_ddl-auto=validate

  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}
      - POSTGRES_USER=${DATASOURCE_USERNAME}
      - POSTGRES_DB=${DATASOURCE_DB}

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
